Add Jack compiler
nand2tetris/web-ide pull request #295
Opened 2024-05-08 07:44 UTC by netalondon

2024-05-09 01:36 UTC, DavidSouther reviewed
Looks like a really great start!

Some initial thoughts, looking forward to seeing it entirely in action!

2024-05-09 01:36 UTC, DavidSouther commented on components/src/stores/compiler.store.ts
> +      await fs.writeFile(`/jack/${name}.jack`, content);
This gets repeated a lot, maybe a `makeJackFilename` helper?

2024-05-09 01:36 UTC, DavidSouther commented on simulator/src/jack/compiler.ts
> +  write(line: string) {
I'd just make this 

```
write(...lines: string[]) {
  this.instructions.push(...lines);
}

this.write("add");
this.write(...expression);
```

2024-05-09 01:36 UTC, DavidSouther commented on simulator/src/jack/compiler.ts
> +      const [prefix, suffix] = call.name.split(".");
`.split(".", 2)` might be a good safety against an "accidental" `foo.bar.baz` name.

2024-05-09 01:36 UTC, DavidSouther commented on web/src/pages/compiler.tsx
> +            <>
I just made a <TabList> and <Tab> helper - https://github.com/DavidSouther/ailly/blob/main/web/src/components/Tabs.tsx

We could copy that over to here and make this much simpler.

2024-05-09 01:36 UTC, DavidSouther commented on web/src/urls.tsx
Reminder to pull this into a separate PR when it's time to release.

2024-05-09 10:08 UTC, DavidSouther requested changes

2024-05-09 10:08 UTC, DavidSouther commented on web/src/shell/tabs.tsx
Could we pull this into its own PR and use it for the test panel first? This this PR only needs to use it

2024-05-09 10:08 UTC, DavidSouther commented on simulator/src/languages/jack.ts
Some tests for parsing at least the example Jack files

2024-05-09 10:08 UTC, DavidSouther commented on simulator/src/jack/compiler.ts
Some compiler tests, please

2024-05-09 11:58 UTC, netalondon commented on simulator/src/languages/jack.ts
Is there a better approach here than to generate the expected cases for each test programmatically?

2024-05-09 14:44 UTC, DavidSouther requested changes

2024-05-09 14:44 UTC, DavidSouther commented on simulator/src/languages/jackSamples.ts
We've usually been putting these in https://github.com/nand2tetris/web-ide/tree/main/projects/src/samples

2024-05-09 14:46 UTC, DavidSouther commented on simulator/src/languages/jack.ts
No, this is good for now. As we run into bugs or errors, focused tests can be very helpful to troubleshoot and isolate, but for now "Parse the sample files" is a good baseline.

2024-05-19 15:32 UTC, DavidSouther approved these changes

2024-05-22 11:24 UTC, DavidSouther approved these changes

2024-05-22 11:24 UTC, merged