Implement full topological sort
nand2tetris/web-ide pull request #328
Opened 2024-05-28 14:41 UTC by netalondon

@DavidSouther turns out we did need a proper topological sort.
This is part of #327

2024-05-29 12:26 UTC, DavidSouther approved these changes

2024-05-29 12:26 UTC, DavidSouther requested changes
(Clicked the wrong button)

2024-05-30 11:44 UTC, DavidSouther requested changes

2024-05-30 11:44 UTC, DavidSouther commented on simulator/src/chip/chip.test.ts
> +  expect(fooC.parts).toEqual([fooC.register, fooC.inc16]);
This currently passes on main without calling sortParts, so I don't think it shows the bug from #327

2024-05-30 11:44 UTC, DavidSouther commented on simulator/src/chip/builder.ts
> +      part.subscribeToClock();
This PR has gotten big enough it's trying to do two things - can we separate out the subscription updates from the sort updates?

2024-05-30 11:44 UTC, DavidSouther commented on simulator/src/chip/graph.ts
> +      const { node, isReturning } = stack.pop()!;
assertExists from `@davidsouther/jiffies` is a low overhead tool to not need the non-null assertion.

2024-05-30 11:44 UTC, DavidSouther commented on simulator/src/chip/graph.ts
> +        stack.push({ node, isReturning: true });
Oh very elegant way to handle this

2024-06-01 13:27 UTC, DavidSouther reviewed
Let me know when this is rebased and the minimal test is in place.

2024-06-02 07:55 UTC, netalondon commented
> Let me know when this is rebased and the minimal test is in place.

I updated the test and now I believe it fails on main.
Did I miss something?

2024-06-03 03:38 UTC, DavidSouther commented on simulator/src/chip/chip.test.ts
> -    expect(fooA.parts).toEqual([fooA.notB, fooA.notA]);
I updated the test in my branch to just look at the IDs, which is the important piece.

2024-06-03 03:40 UTC, DavidSouther commented
I opened #339 to keep the insertion sort, which I maintain is the neater and cleaner approach. But this PR was invaluable in tracking down a test case to make sure we got it right both here and for #327

2024-06-03 03:40 UTC, closed without merging