Update compiler tooltips
nand2tetris/web-ide pull request #332
Opened 2024-06-01 06:15 UTC by netalondon

Closes #331

2024-06-01 13:25 UTC, DavidSouther requested changes

2024-06-01 13:25 UTC, DavidSouther commented on web/src/pages/compiler.tsx
> +                data-tooltip="Open a folder containing Jack file(s)"
These should be localized, I think with the `t` macro?

    data-tooltip={t`Open a folder...`}

Double check the lingui docs for exact syntax.

2024-06-02 07:54 UTC, netalondon commented
Oops, I forgot to push the changes.
Updated now :)

2024-06-02 12:09 UTC, DavidSouther approved these changes

2024-06-02 12:09 UTC, merged