Add local file system functionality to all tools
nand2tetris/web-ide pull request #411
Opened 2024-07-23 10:53 UTC by netalondon

2024-07-24 14:01 UTC, DavidSouther requested changes
I have reviewed the projects part and most of the stores, but I'm getting bogged down in the UI. Can you break this into two PRs - one that updates the project layout and structure, and a second that does the file system user interface?

2024-07-29 08:25 UTC, netalondon commented on package.json
> +    "react-toastify": "^10.0.5"
This is a package to display dismissible toast messages - [react-toastify](https://www.npmjs.com/package/react-toastify)

Looks like this:
![Screenshot from 2024-07-29 11-06-20](https://github.com/user-attachments/assets/6c675b45-e2d4-4a6e-90d1-3b875ba4cf90)

If you have any alternatives in mind let me know.

2024-07-29 08:25 UTC, netalondon commented on simulator/src/test/chiptst.ts
> +    setStatus?: (status: string) => void,
How about `Action<string>` since we use it in other contexts as well?

2024-07-29 08:25 UTC, netalondon commented on simulator/src/test/tst.ts
> +    // if (this.outputFileName) {
Whoops, I wasn't sure if there's any point in writing the output to an actual file.
What do you think?

2024-07-29 14:16 UTC, DavidSouther commented on package.json
> +    "react-toastify": "^10.0.5"
Why can't we use the status bar for this?

2024-07-29 14:16 UTC, DavidSouther commented on simulator/src/test/chiptst.ts
> +    setStatus?: (status: string) => void,
Sounds great!

2024-07-29 14:26 UTC, DavidSouther commented on simulator/src/test/tst.ts
> +    // if (this.outputFileName) {
I think there is in some contexts. For instance, I have in the back of my mind a project to implement the 8086 chip following Code (Charles Petzold). If I did that, I would want to write the chip, manually verify it, write the tests, manually verify them, and then generate the output file. So that seems like this should be an available feature, but maybe in the CLI? Or we can remove it here and the CLI runner could have a flag and write the complete output file on its own, separate from the execution.

So I think I've talked myself into suggesting removing it here for now!

2024-07-30 09:09 UTC, netalondon commented on package.json
> +    "react-toastify": "^10.0.5"
I guess it bothered me that this will obscure the usual message `HDL code: No syntax errors`, but now that I think about it, it's not essential since we have error highlighting in the editor.

I'll use the status bar for now.

2024-07-30 14:15 UTC, DavidSouther requested changes
Again, I was able to review changes in projects/ and most of simulator/ and components, but please pull out (at least) web/ and related changes to a separate PR.

Looks like there's maybe four changes in here?

1. setStatus to Action
2. Project test structure
2b. Project files with updated load instructions
3. Web shell to create files

2024-07-30 14:15 UTC, DavidSouther commented on package.json
> +}
(nit) missing ending newline

2024-07-30 14:15 UTC, DavidSouther commented on simulator/src/loader.ts
> +  console.log(asm);
(nit) remove from debugging

2024-07-30 14:15 UTC, DavidSouther commented on simulator/src/test/chiptst.ts
> +  ): Result<ChipTest, Error> {
Please change this to an object initializer

2024-07-30 14:15 UTC, DavidSouther commented on simulator/src/test/cputst.ts
> +    compareTo?: Action<string>,
Object initializer, please

2024-07-30 14:15 UTC, DavidSouther commented on simulator/src/test/vmtst.ts
> +    compareTo?: Action<string>,
Object Initializer

2024-07-30 14:15 UTC, DavidSouther commented on web/src/pages/asm.tsx
> +        return await actions.step();
This is going to be an issue "in the future" when we go to make test files run "as fast as possible", but I don't have a decent way to resolve the async fs with all operations being sync; that'll probably need a significant refactor of the test file format itself.

2024-07-31 06:21 UTC, netalondon commented
> Again, I was able to review changes in projects/ and most of simulator/ and components, but please pull out (at least) web/ and related changes to a separate PR.
> 
> Looks like there's maybe four changes in here?
> 
> 1. setStatus to Action
> 2. Project test structure
>    2b. Project files with updated load instructions
> 3. Web shell to create files

Sorry I missed your last comment about this. Will do.

2024-07-31 11:46 UTC, netalondon commented on simulator/src/languages/grammars/tst.ohm.js
> +  filename = (letter|underscore|dot|dollar|minus) (alnum|underscore|dot|dollar|minus)*
Both uses are in the TST grammar, we have two copies of each grammar file - `tst.ohm` and `tst.ohm.js`.
I'm not actually sure why that is, was there a specific reason you can recall?

2024-09-10 22:19 UTC, DavidSouther approved these changes

2024-09-10 22:22 UTC, merged