Add watch script
nand2tetris/web-ide pull request #478
Opened 2024-09-19 18:25 UTC by happytomatoe

2024-09-20 11:47 UTC, DavidSouther requested changes

2024-09-20 11:47 UTC, DavidSouther commented on build-watch.js
This build-watch file seems like overkill - the set of projects is well known, and simply listing each one should be fine.

1. Add a `watch` target in each package (components, projects, simulator) that does `npm run build -- --watch`
2. Add a `watch` target in the root, which calls those directly using concurrently: `conc \"npm run -w components watch\" \"npm run -w projects watch\" \"npm run -w simulator watch\"`

2024-09-20 16:25 UTC, happytomatoe commented on build-watch.js
Changed

2024-09-22 02:23 UTC, DavidSouther commented on package.json
> +}
(nit) ending newline got lost

2024-09-22 02:24 UTC, DavidSouther commented on package.json
> +    "watch": "concurrently -k --restart-tries 3 \"npm run build -w components -- -w \" \"npm run build -w projects -- -w\" \"npm run build -w runner -- -w\" \"npm run build -w simulator -- -w\"   ",
Could you clean up the whitespace in here a bit? Sometimes there's extra spaces before and after the \", sometimes not.

2024-10-02 17:09 UTC, happytomatoe commented on package.json
> +    "watch": "concurrently -k --restart-tries 3 \"npm run build -w components -- -w \" \"npm run build -w projects -- -w\" \"npm run build -w runner -- -w\" \"npm run build -w simulator -- -w\"   ",
if you mean at then end - done

2024-10-02 17:09 UTC, happytomatoe commented on package.json
> +}
added newline

2024-10-03 19:08 UTC, DavidSouther approved these changes

2024-10-03 19:09 UTC, merged