Feat/compiler
nand2tetris/web-ide pull request #483
Opened 2024-10-03 12:28 UTC by happytomatoe

2024-10-03 12:30 UTC, happytomatoe commented on simulator/package.json
> +    "assert": "^2.1.0",
this is needed by ANTLR. I don't know why. They have support for many languages. Typescript is not their best one.

2024-10-03 12:31 UTC, happytomatoe commented on simulator/src/jack/builtins.ts
> +  //TODO: what is this?
Would be great if someone could answer this

2024-10-03 12:39 UTC, happytomatoe commented on simulator/src/jack/listener/binder.listener.ts
> +    if (ctx.subroutineType().CONSTRUCTOR() != null) {
funny fact - Parser returns null if rule wasn't used.

2024-10-03 13:10 UTC, happytomatoe commented on simulator/src/jack/listener/validator.listener.ts
> +        this.#addError(
what convention do we use for private methods? Using ts private modifier doesn't make sense as we are using JS artifacts

2024-10-03 19:15 UTC, DavidSouther commented on simulator/src/jack/builtins.ts
> +  //TODO: what is this?
These are described in the second paragraph of section 12.3 of The Elements of Computing Systems.

> Init functions: Some OS classes use data structures that support the implementation of some of their subroutines. For each such OSClass, these data structures can be declared statically at the class level and initialized by a fucntion which, by convention, we call OSClass.init. The init functions are for internal purposes and are not documented in the OS API.

While they are not documented in the book, they are necessary to be defined for Jack programs that explicitly call them.

2024-10-03 19:24 UTC, RomanLukash340 commented
Upd: I've added validate method to the compiler. Now after each keystroke time of execution is under 100ms for [many big files](https://github.com/nand2tetris/web-ide/issues/447).

2024-10-04 06:02 UTC, RomanLukash340 commented on simulator/src/jack/builtins.ts
> +  //TODO: what is this?
Changed

2024-10-04 06:19 UTC, RomanLukash340 commented on .vscode/launch.json
> +    },
run web ide doesn't work for me(vscode doesn't stop at the breakpoint place ). That's why I've added additional

2024-10-04 06:24 UTC, RomanLukash340 commented on simulator/src/jack/resources/test/Average/Main.jack
> +// This file is part of www.nand2tetris.org
Would gladly accept suggestions if this the wrong folder for these files

2024-10-04 07:09 UTC, RomanLukash340 commented
qq - why do we write VM files to fs?

2024-10-07 09:15 UTC, happytomatoe commented
@DavidSouther @netalondon just FYI - I've created new repo for [jack language server protocol](https://github.com/happytomatoe/nand2tetris-jack-lsp), I would gladly contribute this to nand2tetris repo.
About this PR - I would rather have extract compiler into its' own package because of the new repo

2024-10-07 11:14 UTC, DavidSouther commented
Great work in here, I've been following your WIP as it goes.

We're happy to have the LSP in this repo, we just need to spend a bit thinking through where it will go, how to extend it to the other languages, and how to integrate it with the web, cli, and ide extensions.

Again, your use case as a "Jack developer" is relatively niche in the NAND2Tetris community. The vast bulk of work happens at the Hack level, and a little bit at the VM and assembly levels. Improvements to those will have the most impact for NAND2Tetris students.

So finding a migration path from the current state to your ANTLR based approach is a good project for quarter, if someone wanted to pick that up.

Are you ready for me to review this PR?

2024-10-07 11:39 UTC, happytomatoe commented
@DavidSouther  Please go ahead. There is a possibility that I can find some small bugs. I can create another PR, if you would like, to fix them.

2024-10-07 15:36 UTC, DavidSouther commented
>  As you can see that 1 key stroke calls compiler 2 times on screenshot.

In dev, yes; in production, it should still only be called once. That said, we can probably make better use of effects to ensure it happens only once either way.

2024-10-07 17:43 UTC, DavidSouther requested changes
Great work on getting this updated compiler working! Love it big picture. I have a variety of comments - some are small nitpicks on style things that Prettier doesn't capture. Some are suggestions for using utility libraries and classes that the project uses consistently.  I have a few suggestions for improving a couple pieces of the design implementation, happy to have a longer conversation on those.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/symbol.ts
> +  lookup(name: string): VariableSymbol | undefined {
(nit) here and elsewhere - one blank line between declarations

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/binder.listener.test.ts
> +import fs from "fs";
I know it's a bit more work, but please use the `fs` abstraction from Jiffies that's used elsewhere in the project. It allow much easier mocking and replacement later on.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/binder.listener.ts
> +        ctx.className()!.start.line,
Maybe extract ctx.className one time?

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/binder.listener.ts
> +    const id = ctx.className()!.IDENTIFIER();
Prefer the `assertExists` utility to the `!` type override operator.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/error.listener.ts
> +    recognizer: Recognizer<any>,
No any, anywhere. `unknown` is acceptable.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/validator.listener.test.ts
> +  test("call function - undeclared variable ", () => {
It looks like most of these are just doing the same `testValidator` call, so you could probably use `test.each` for a parameterized or data-driven test. https://vitest.dev/api/#test-each

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/validator.listener.ts
> +import {
I would actually do a * import for these ones, and do `errors.FieldCantBeReferencedInFunction` or similar throughout this file.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/validator.listener.ts
> +        this.#addError(
Why do you need to block anyone else from calling addError? I don't know how anyone would get a reference to an instance of the validator outside the tree, so it doesn't seem particularly worthwhile to have these as private.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/validator.listener.ts
> +   * Var name when doing some actions - do statement, let ... We have a different rule for a var name that is used in declaration
I can't quite follow this comment. Please use complete English sentences in docblock comments.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/validator.listener.ts
> +   * Control flow
This isn't a particularly helpful comment - it's meant as a section separator, but it's written as a docblock attached to enterWhileStatement. I would suggest simply removing it.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/validator.listener.ts
> +      const type = this.localSymbolTable.lookup(ctx.varName()!.getText())!.type;
As elsewhere, `assertExists` in lieu of `!` assertions.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/validator.listener.ts
> +      throw new Error("Something went wrong - CFG has only right  subtree");
(nit) 2 spaces

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/validator.listener.ts
> +  }
Don't mix output into data classes. This can simply return the string, and allow the caller to decide how to handle the IO.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/vm.writer.listener.ts
> +/* eslint-disable  @typescript-eslint/no-non-null-assertion */
Don't disable eslint.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  private afterEquals = false;
I would maybe change this name to `inAssignmentRightHandSide`? I think that's how it's being used? It only becomes true when reviewing the assignment operator to end of statement, and Jack doesn't allow multiple assignment.

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  private currentLabelInd = 0;
Prefer `Index` to `Ind`

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  public result = "";
I would suggest keeping a bit of structure here, and storing this not as the program text of the VM code, but instead using the VM language primitives. We can then use that serialization (or, load that directly into the VM emulator)

2024-10-07 17:43 UTC, DavidSouther commented on simulator/src/jack/compiler.ts
Rather than deleting this file, could you create a second `antlr_compiler.ts` class, and we'll delete this one later?

2024-10-07 21:33 UTC, happytomatoe commented on components/src/stores/compiler.store.ts
> +    },
What's the rule here? Can we add this to prettier?

2024-10-07 21:34 UTC, happytomatoe commented on components/src/stores/compiler.store.ts
> +    },
Please ignore the piece about prettier

2024-10-08 06:37 UTC, happytomatoe commented on simulator/README.md
Could you check if it looks ok now?

2024-10-08 06:38 UTC, happytomatoe commented on .gitignore
> +**/.antlr
Done

2024-10-08 06:46 UTC, happytomatoe commented on simulator/src/jack/listener/vm.writer.listener.ts
> +/* eslint-disable  @typescript-eslint/no-non-null-assertion */
Can I ask why? Antlr returns nulls  if the derivation didn't happen in some case(let's say we have static instead of field keyword) . In this file I need to assure compiler that after I've checked that some property is not null using "!". 
Should I just remove this and leave the compiler warnings?

2024-10-08 06:51 UTC, happytomatoe commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  public result = "";
What are the vm language primitives? Do you mean the instructions array(array of strings)?

2024-10-08 06:51 UTC, happytomatoe commented on simulator/src/jack/compiler.ts
sure

2024-10-08 07:08 UTC, happytomatoe commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  private currentLabelInd = 0;
Done

2024-10-08 07:08 UTC, happytomatoe commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  private afterEquals = false;
Done

2024-10-08 07:08 UTC, happytomatoe commented on simulator/package.json
> +    "test-jack": "npm run test -- -t \"Jack\"",
Removed

2024-10-08 07:43 UTC, happytomatoe commented on simulator/src/jack/builtins.ts
> +export const intRange = { min: -32768, max: 32767 } as Range;
Done

2024-10-08 07:43 UTC, happytomatoe commented on simulator/src/jack/builtins.ts
> +const builtInClasses = [
Done

2024-10-08 07:44 UTC, happytomatoe commented on simulator/src/jack/error.ts
> +export interface Span {
Changed

2024-10-08 07:45 UTC, happytomatoe commented on simulator/src/jack/error.ts
> +  public span: Span;
Thank you! Changed

2024-10-08 07:46 UTC, happytomatoe commented on simulator/src/jack/error.ts
> +export class LexerOrParserError extends JackCompilerError {}
Yes, please provide code suggestion. From my standpoint I use this because it's easier to check in the tests the error type rather than message

2024-10-08 07:47 UTC, happytomatoe commented on simulator/src/jack/error.ts
> +    Object.setPrototypeOf(this, UnknownSubroutineCallError.prototype);
Deleted. Previously this  class extended error type.

2024-10-08 09:41 UTC, happytomatoe commented on simulator/src/jack/listener/binder.listener.test.ts
> +import fs from "fs";
Sorry, that doesn't make sense to me as fs abstraction doesn't have synchronous methods to read a file or a directory.  Is there any other approach rather than using callback function (I mean .then method)?

2024-10-08 09:49 UTC, happytomatoe commented on simulator/src/jack/listener/binder.listener.ts
> +export class BinderListener extends JackParserListener {
Because this concept is used for typescript. Please suggest better name

2024-10-08 09:56 UTC, happytomatoe commented
> > So finding a migration path from the current state to your ANTLR based approach is a good project for quarter, if someone wanted to pick that up.
> 
> @DavidSouther Can you create a new repo? I would provide the scaffolding along with the jack lsp implementation

Nvm. I don't want to spend my time on that.

2024-10-08 14:01 UTC, DavidSouther commented on components/src/stores/compiler.store.ts
> +    },
Yeah, unfortunately I don't think prettier supports it at this time. I believe Rome might? But I haven't looked into it closely.

Broadly, separate top-level and class-level function declarations by one blank line. Top level and class level properties and variables can be grouped without blank lines between them "so that it looks good" - I know that's not a great rule, but there's room for a bit of aesthetics. "Keep similar things together" is the principle there, but not super strict.

But for the rule - every function should have a blank line before it (or before its docblock, if it has a comment)

2024-10-08 14:04 UTC, DavidSouther commented on components/src/stores/compiler.store.ts
> +    async writeNewFile(name: string, content?: string) {
So, this one and `validate` should have a blank line before them, but `reset` and `compile` look good.

2024-10-08 14:04 UTC, DavidSouther commented on simulator/README.md
The write up in [simulator/src/jack/README.md](https://github.com/nand2tetris/web-ide/pull/483/files/#diff-7212235467ce085d36f890e059c2b3082d4c1f581a429fcd9513888199c6408f) is great, thank you!

2024-10-09 03:33 UTC, DavidSouther commented on simulator/src/jack/error.ts
> +export class LexerOrParserError extends JackCompilerError {}
What about this? https://github.com/happytomatoe/web-ide/pull/4

2024-10-11 17:58 UTC, DavidSouther commented
@happytomatoe I hope you're able to keep making progress on this, but I wanted to let you know that I'm unavailable for the coming week. I'll be back October 20th to review any changes.

2024-10-11 18:02 UTC, happytomatoe commented on components/src/stores/compiler.store.ts
> +    },
Is this what are we looking for?
https://stackoverflow.com/questions/52772097/how-to-add-new-line-after-and-before-method-declarations-in-classes-using-pretti

2024-10-11 18:05 UTC, DavidSouther commented on components/src/stores/compiler.store.ts
> +    },
Ah, it's a part of eslint, not prettier, that's probably why I couldn't find it.

2024-10-11 18:11 UTC, DavidSouther commented on simulator/src/jack/error.ts
> +export class LexerOrParserError extends JackCompilerError {}
You're probably thinking of their `Diagnostic` interface, which does something similar albeit using Number for identifying the error code, rather than a string. Regardless of formatting and style, a class hierarchy is not the correct approach in TS. Happy to iterate the tagged union to something you find more readable, but it will not be class based.

2024-10-11 18:12 UTC, DavidSouther commented on simulator/src/jack/compiler.ts
Looks good.

2024-10-11 18:22 UTC, happytomatoe commented on simulator/src/jack/listener/binder.listener.test.ts
> +import fs from "fs";
Thank you! Changed.

2024-10-11 18:24 UTC, happytomatoe commented on simulator/src/jack/listener/binder.listener.test.ts
> +function testBinder<T extends { name: string }>(
Great! I didn't know that this could be done this way. Thank you!

2024-10-11 18:33 UTC, happytomatoe commented on simulator/src/jack/listener/binder.listener.ts
> +export class BinderListener extends JackParserListener {
Changed to JackGlobalSymbolTableListener

2024-10-11 18:43 UTC, happytomatoe commented on simulator/src/jack/listener/binder.listener.ts
> +    const id = ctx.className()!.IDENTIFIER();
Done

2024-10-11 18:43 UTC, happytomatoe commented on simulator/src/jack/listener/binder.listener.ts
> +        ctx.className()!.start.line,
Done

2024-10-11 18:44 UTC, happytomatoe commented on simulator/src/jack/listener/common.ts
> +export enum CallType {
@DavidSouther Can I ask you why? I specially used int enum for this to be faster. I guess ANTLR uses the same strategy

2024-10-11 18:52 UTC, happytomatoe commented on simulator/src/jack/listener/binder.listener.ts
> +/* eslint-disable  @typescript-eslint/no-non-null-assertion */
Done

2024-10-11 18:52 UTC, happytomatoe commented on simulator/src/jack/listener/error.listener.ts
> +    recognizer: Recognizer<any>,
Changed

2024-10-11 18:54 UTC, happytomatoe commented on simulator/src/jack/listener/vm.writer.listener.ts
> +/* eslint-disable  @typescript-eslint/no-non-null-assertion */
Added assertExists function calls to satisfy compiler

2024-10-11 18:55 UTC, happytomatoe commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  public result = "";
May I ask why it's done this way?

2024-10-11 18:58 UTC, DavidSouther commented on simulator/src/jack/listener/common.ts
> +export enum CallType {
It's... complicated. TypeScript Enum syntax was an early addition to the language, that would not be allowed today. It adds behavior that isn't present in JavaScript, and achieves it by writing weird surjective object literals. There are a couple places where that's a good thing, but generally using string literal unions as enums (which don't use the `enum` keyword) are a little bit cleaner.

More importantly, the preferred way in this project.

https://www.typescriptcourse.com/string-literal-unions-over-enums for more reading.

2024-10-11 19:00 UTC, happytomatoe commented
> @happytomatoe I hope you're able to keep making progress on this, but I wanted to let you know that I'm unavailable for the coming week. I'll be back October 20th to review any changes.

Have a nice holiday)

2024-10-11 19:01 UTC, DavidSouther commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  public result = "";
I'm not sure I understand what you're asking for an explanation on?

Why does VmInstruction exist? As an interface describing the structures in a valid Jack VM program.

Why would I suggest using the VmInstruction[] type over string? Because you retain more information for longer in the lifetime of the program. By going directly to string, you immediately discard significant amounts of information that the program already computed.

2024-10-11 19:09 UTC, happytomatoe commented on simulator/src/jack/error.ts
> +export class LexerOrParserError extends JackCompilerError {}
Let's use Diagnostics interface.

2024-10-11 19:21 UTC, DavidSouther commented on simulator/src/jack/error.ts
> +export class LexerOrParserError extends JackCompilerError {}
You probably don't want the entirety of [`Diagnostic`](https://github.com/microsoft/TypeScript/blob/a53c37d59aa0c20f566dec7e5498f05afe45dc6b/src/server/protocol.ts#L2570), just the subset that I included in the other PR.

"That's hard to read" is subjective - what do you find hard to read about it? Happy to iterate on it, but I need to know what you're pushing back on.

2024-10-11 19:28 UTC, happytomatoe commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  public result = "";
Why we do we use array for that?

2024-10-11 19:30 UTC, DavidSouther commented on simulator/src/jack/error.ts
> +export class LexerOrParserError extends JackCompilerError {}
(I just noticed that I somehow missed running Prettier on that PR; does it look better with a little formatting applied?)

2024-10-11 19:35 UTC, DavidSouther commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  public result = "";
Ah, because it's the easiest "next step" from string, so it also keeps the most similarity with your current code. 

Instead of `this.result += "    call Memory.alloc 1 \n";`,  you can have `this.result.push({op: "call", name: "Memory.alloc", nArgs: 1});`

2024-10-17 15:33 UTC, happytomatoe commented on components/src/stores/compiler.store.ts
> +    },
Let's agree that we can create another PR and standardize this across whole codebase

2024-10-17 15:40 UTC, happytomatoe commented on simulator/src/jack/error.ts
> +export class LexerOrParserError extends JackCompilerError {}
Looks better now. I guess we won't get many compiler errors typically.

2024-10-17 15:43 UTC, happytomatoe commented on simulator/src/jack/listener/common.ts
> +export enum CallType {
Luckily VS code lang server has a pattern for this
```
export declare namespace InsertTextFormat {
    const PlainText: 1;
    const Snippet: 2;
}
export type InsertTextFormat = 1 | 2;
```

2024-10-20 09:04 UTC, happytomatoe commented
Small update - I was fed up working with official antlr4 typescript target. Migrated to  [antlr4ng](https://github.com/mike-lischke/antlr4ng)

2024-10-20 09:38 UTC, happytomatoe commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  public result = "";
This is a separate change.
Correct if I am wrong - This [function](https://github.com/nand2tetris/web-ide/blob/634686eca2bbb6c0f795bf72f1e2f440647f02e5/simulator/src/jack/compiler.ts#L63C1-L65C47) has return type `Record<string, string | CompilationError> `. Current compiler creates an array of strings and then joins the lines inside this [function](https://github.com/nand2tetris/web-ide/blob/634686eca2bbb6c0f795bf72f1e2f440647f02e5/simulator/src/jack/compiler.ts#L215).

2024-10-21 17:50 UTC, DavidSouther commented
> Small update - I was fed up working with official antlr4 typescript target. Migrated to [antlr4ng](https://github.com/mike-lischke/antlr4ng)

Have you looked at Treesitter at all? (question, not a suggestion, but I hear great things about it and might be where I'd start if I was going from scratch today).

2024-10-21 18:59 UTC, DavidSouther requested changes
Looking great, these are mostly optional thoughts at this point, up to you to incorporate them now or hold off a bit.

2024-10-21 18:59 UTC, DavidSouther commented on components/src/stores/compiler.store.ts
> +    },
Ok. Please do your best in the meantime to keep this as tidy as you can.

2024-10-21 18:59 UTC, DavidSouther commented on simulator/src/jack/symbol.ts
>  export type GlobalSymbolTable = Record<string, GenericSymbol>;
I see in several places this is used specifically as a map, rather than an ad-hoc object. Should this be `Map<string, GenericSymbol>`? It'll enforce type checking the possibly null `.get` response, but will also make it easier to check `.size` instead of `Object.keys(...)`

(Edit: this is the current interface with the `compile`, so that would also need to change. Agreed to do that leter.)

2024-10-21 18:59 UTC, DavidSouther commented on simulator/package.json
> +    "antlr4ng": "^3.0.7",
Does this change need a change in the README?

2024-10-21 18:59 UTC, DavidSouther commented on simulator/src/jack/anltr.compiler.ts
> +  const errors: Record<string, CompilationError> = {};
For most of these - are these Objects or Maps? (It's OK if they're records, but please leave a comment if that's a specific design choice, and why Record is preferred to Map)

2024-10-21 18:59 UTC, DavidSouther commented on simulator/src/jack/anltr.compiler.ts
> +    const vmWriter = new VMWriter(
Ahh, I added a comment earlier about Record vs Map, but VMWriter wants a Record. Hmm, maybe that should have been a Map too. Up to you to change to using Maps, or acknowledging the comment and moving on.

2024-10-21 18:59 UTC, DavidSouther commented on simulator/src/jack/antlr.compiler.test.ts
This could be a fancy "golden file" test, where each jack/vm pair are their own files, which are loaded and discovered at runtime... but that's a lot of work and this is working for now. If anyone sees this review comment in the future, you might go for it then.

2024-10-21 18:59 UTC, DavidSouther commented on simulator/src/jack/listener/vm.writer.listener.ts
> +  public result = "";
Well... I should have made this comment there! Fine leaving the interface and we can come back to it later.

2024-10-22 06:34 UTC, happytomatoe commented on simulator/package.json
> +    "antlr4ng": "^3.0.7",
I've already changed the readme. Both of this libraries implement the same api/interfaces

2024-10-22 06:35 UTC, happytomatoe commented on simulator/package.json
> +    "antlr4ng": "^3.0.7",
This library already has a ton of comments in typescript sources so I don't know if makes sense to add anything else in terms of documentation

2024-10-22 06:43 UTC, happytomatoe commented on simulator/src/jack/anltr.compiler.ts
> +  const errors: Record<string, CompilationError> = {};
These are maps. I will change it

2024-10-22 07:02 UTC, happytomatoe commented
> > Small  update  -  I  was  fed  up  working  with  official  antlr4  typescript  target.  Migrated  to  [antlr4ng](https://github.com/mike-lischke/antlr4ng)
> 
> Have you looked at Treesitter at all? (question, not a suggestion, but I hear great things about it and might be where I'd start if I was going from scratch today).

What do you hear specifically? I don't see typescript API on their page. So it's the same pain as using official antlr javascript library. And it's also a pure C library with language bindings. I don't know if this has it's own issues. 
I've seen this tool when I was building prettier plugin for Jack as it can build syntax tree(Tree with whitespaces and comments.)

If you would build this from scratch, based on my experience, the most go to options are 
- Antlr - because it's old and mature. There are commercial companies that use  this tool - [https://strumenta.com/](https://strumenta.com/). There are a lot documentation/resources that can help with specific problem. On the main website looks like Python used this library before switching to own implementation.
- Chevrotain - I've seen java prettier plugin and probably of others prettier plugins that use chevrotain. If comparing with previous option it probably is faster (according to their benchmark). Though we probably don't need a faster lexer/parser. I don't know how mature is this library. I've seen a PR where they are implementing a feature from ANTLR. I also don't know if there are commercial companies that use it.

2024-10-22 17:01 UTC, happytomatoe commented on simulator/src/jack/anltr.compiler.ts
> +  const errors: Record<string, CompilationError> = {};
@DavidSouther  Why to choose Map in these cases?

2024-10-22 17:02 UTC, happytomatoe commented on simulator/src/jack/anltr.compiler.ts
> +  const errors: Record<string, CompilationError> = {};
After doing a small research on this topic I don't see any substantial difference other that a little bit better api.

2024-10-22 17:14 UTC, happytomatoe commented on simulator/src/jack/antlr.compiler.test.ts
For whomever reads this comment - this is partially done if you look inside jack/resources/test folder. I didn't want to do this for small code snippets because I am lazy and don't want to be jumping across files in the editor.

@DavidSouther Let me know if you want me to change the path for jack/resources/test.

2024-10-22 17:22 UTC, happytomatoe commented on components/src/stores/compiler.store.ts
> +    },
Let me know if you want me to change something. Otherwise I will leave it as it is

2024-10-22 17:23 UTC, happytomatoe commented
Testing is done from my subjective point of view.

2024-10-23 17:07 UTC, DavidSouther approved these changes

2024-10-23 17:07 UTC, DavidSouther commented on simulator/src/jack/antlr.compiler.test.ts
All good.

2024-10-23 17:07 UTC, DavidSouther commented on simulator/src/jack/symbol.ts
> +const scopeTypeToStringMap: Record<ScopeType, string> = {
I think `ScopeType` could have been `export type ScopeType = 'static'|'this'|'argument'|'local'';`

Then we wouldn't have needed scopeTypeToStringMap at all. Not a big deal wither way.

2025-09-09 04:37 UTC, closed without merging